### PR TITLE
Add 'previewGridClasses', 'previewGridProps' props

### LINKED ISSUE #85: Is there any way to customize the preview list?
I'm noticing hardcoded values for the spacing in the preview list. If I want to change that stuff, my only option is to fork the repo, right?

### PR DESCRIPTION
**Pull request by loongyh**
Add props to customize the `previewList` grid spacing and columns.
Fixes #85

### CODE REVIEW

**Comment by max-carroll** [comment]
I also want to customise the preview, but it may not be limited to spacing, why don't we just allow PreviewProps to be passed in then we spread them out on the Preview Grid component,

i.e. we might want PreviewProps={
   spacing: 3,
   xs: 3,
   style: {
      border: '2px solid dashed'
   }
}

then you could have <Grid {...PreviewProps}> Then we would be able to customise many things not just spacing. I dont think this is very sustainable this pattern of having every detail of very granular things defined like this e.g. previewSpacing, previewColumns, Because if I wanted to have a preview Style, then what if we want 5 more are we going to continue with this pattern?

Would it not make more sense to have these collected together in an object?

**Comment by max-carroll** [comment]
however I also would really like some way of adding a style or className to it so if this is the pattern we have  to go with then we have to go with it, wish I would have some time to help out in contributing to this, I will help out if I get some time in the next few weeks

**Comment by loongyh** [comment]
@max-carroll yep agreed component props makes more sense i shall revise my pr

**Comment by max-carroll** [comment]
Thanks loongyh, this will also help me as I want to override the style of it a bit. For me I'm using it for an image upload, where you can only upload one file, so I will probably make the column width of the preview 12 and then see if I can use the styles to make it take the whole area of the box, I may have to make further changes like perhaps hiding the "drag  files here text" when the drop zone becomes occupied

**Comment by loongyh** [comment]
> Looks good, wondering whether we might want to also allow a className or style to be provided to that grid, however this maybe scope creep.
> 
> also about the 8px rule for spacing, I know it says that on the material UI website, but is this not multiples of what ever you have configured for your theme.spacing(1) in your mui theme?

hmm if it’s based on theme.spacing() and not 8px then the MUI docs needs updating. anyway pls don’t merge first i’ll see what can be improved for this pr

**Comment by max-carroll** [comment]
I could be wrong about the 8px thing, this was just an assumption I made

**Comment by loongyh** [comment]
Implemented @max-carroll's suggestions, example props:
`previewGridProps={{container: {spacing: 5}, item: {xs: 6}}}`
`previewGridClasses={{item: classes.item}}`

**Pull request merged**
