### PR TITLE
removing css in favor of all jss styling

### LINKED ISSUE #6: use only JSS for styling (no CSS)
It would be more consistant if _material-ui-dropzone_ only used CSS or JSS, instead of both.  An all JSS solution might be the better route to align with Material-UI v4 goals.

### PR DESCRIPTION
**Pull request by haysclark**
I did not include the 'dist' content from the build process, let me know if that should be included.

Resolves #6

### CODE REVIEW

**Comment by haysclark** [comment]
@jackpilowsky Sure thing, I wasn't sure if you wanted to prepare the build.

I also just noticed that my code is causing some hitching in the animation... I'll see if I can sort is out.

**Comment by haysclark** [comment]
Here is the corrected commit which includeds the _dist_ folder.  I also removed the linting that was included in the original commit.

**Comment by jackpilowsky** [comment]
Looks good to me, but I don't have the ability to commit. Only @Yuvaleros does

**Comment by haysclark** [comment]
@jackpilowsky Ack! I found an big issue. 😞 I missed the fact that JSS is throwing some errors.

```
browser.js:49 Warning: [JSS] Unknown at-rule @-webkit-keyframes progress
browser.js:49 Warning: [JSS] Unknown at-rule @-moz-keyframes progress
browser.js:49 Warning: [JSS] Unknown at-rule @-ms-keyframes progress
```

I'm trying to hunt down a resolution.

**Comment by jackpilowsky** [comment]
We problably don't need those vendor-prefixes

**Comment by jackpilowsky** [comment]
Material UI includes jss-vendor-prefixer: https://material-ui.com/customization/css-in-js/

**Comment by haysclark** [comment]
@jackpilowsky Awesome! Thanks for the heads up.  I wasn't sure if they were needed because _@-webkit-keyframes progress_, _@-moz-keyframes progress_, _@-ms-keyframes progress_ all had a value of 75, while _@keyframes progress_ had a value of 70.

I tested the code in Firefox, Chrome which both look correct. The animations do not run in Safari, but this is not a regression as the original CSS version does not animate in Safari either.

I think we are good now. 🤞

**Comment by haysclark** [comment]
@jackpilowsky Do you think these lines should go as well?

https://github.com/Yuvaleros/material-ui-dropzone/blob/24f08088dae3c103913b18dba946d5fe024a174a/src/DropzoneArea.js#L34-L35

and

https://github.com/Yuvaleros/material-ui-dropzone/blob/24f08088dae3c103913b18dba946d5fe024a174a/src/DropzoneArea.js#L42-L43

**Comment by haysclark** [comment]
All vendor-prefixing removed and code build to the /dist folder.

**Comment by jackpilowsky** [comment]
Looks good

**Pull request merged**
