### PR TITLE
Update turned into rewrite

### PR DESCRIPTION
**Pull request by jackpilowsky**
I started working on to update this to run material-ui >= 1.x and react 16.x and I changing a lot of stuff:

- Had to change the dev environment. I couldn't get browserify/babel settings right when updating them. I switched it to use create-react-library. 
- Set up prop-types to make debugging easier for the users of this module. 
- Switched styles to use Material-UI's withStyles
- Replaced some the Bootstrap-like rows and columns with Material-UI Grid components.
- Separated the components for the Dialog and the Dropzone functionality. 
- Broke up the export into named exports so that users can get the dropzone functionality outside the dialog. 
- Added styled Snackbars: green for drops, blue for deletes, red for rejected files.

### CODE REVIEW

**Comment by Yuvaleros** [comment]
@jackpilowsky Thank you! looks great! I just noticed you dropped the "allowed/not allowed" stripe effects. was that intentional?

**Comment by jackpilowsky** [comment]
Material-ui’s withStyles don’t support keyframes. Maybe it will be better to go back to CSS or SASS for that


Sent from Yahoo Mail for iPhone


On Saturday, November 3, 2018, 7:32 AM, Yuvaleros <notifications@github.com> wrote:


@jackpilowsky Thank you! looks great! I just noticed you dropped the "allowed/not allowed" stripe effects. was that intentional?

**Comment by jackpilowsky** [comment]
Ok, the stripe animations are working again with this latest commit

**Comment by Yuvaleros** [comment]
Merged. Thanks for the help!

**Comment by jackpilowsky** [comment]
No problem. Remember to also publish the new version to NPM

**Comment by Yuvaleros** [comment]
Done.

**Pull request merged**
