### PR TITLE
Added missing properties to type definition

### PR DESCRIPTION
**Pull request by JLuboff**

### CODE REVIEW

**Comment by katsadim** [comment]
Please merge this PR. I have to do the following in order to mute the typescript compiler:
```typescript
{/*
// @ts-ignore */}
```

**Comment by is343** [comment]
@JLuboff since you already have a PR pending, can you also add the '[Get Alert Message](https://github.com/Yuvaleros/material-ui-dropzone#dropzonearea-componet-get-alert-messages)' props to your definitions?

**Comment by JLuboff** [comment]
@is343 I've been out of town/busy but I'll look into adding those if not over the weekend than early next week and we'll see if we can get this PR merged.

**Comment by JLuboff** [comment]
@is343 Updated to include Get Alert messages. 
@Yuvaleros Any chance you can review and merge? Thanks!

**Comment by Yuvaleros** [comment]
Added, thanks guys!

**Pull request merged**
