### PR TITLE
added rendering of existing files

### PR DESCRIPTION
**Pull request by georgiydubrov**
fix https://github.com/Yuvaleros/material-ui-dropzone/issues/56

added possibility to define urls of already uploaded images

### CODE REVIEW

**Comment by Yuvaleros** [comment]
Thanks!

**Comment by dasturchiuz** [comment]
Not Working 
 initialFiles={["<base_url>/1231212.jpg"]}

**Comment by georgiydubrov** [comment]
> Not Working
> initialFiles={["<base_url>/1231212.jpg"]}
> Pls update version

You need to use backticks and not double quotes
[Template literals MDN link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)
If it's misprinting in the example can you provide more details, maybe you've got any errors?

**Comment by sebinievas** [comment]
`initialFiles` is not an available property for me. Was this lost somehow?

**Pull request merged**
