### PR TITLE
[BREAKING] Upgrade react-dropzone to version 10

### PR DESCRIPTION
**Pull request by panz3r**
This PR upgrade `react-dropzone` to version `10.2.1` and updates the implementation to match the new component usage.

This PR introduce a breaking change since `react-dropzone` v10+ dropped support for `react` versions older than v`16.8` (see release notes [here](https://github.com/react-dropzone/react-dropzone/releases/tag/v10.0.0)).

Also this PR drops support for `material-ui` version `3`.

I'd suggest this to be a `major` version bump for `material-ui-dropzone` (so bump to version `3.0.0`) and, if support for older versions of `react` and `material-ui` is still required, you can think to keep a `v2` branch with the previous implementation so that users of this library can decide to use `v2.x` or `v3.x` based on their needs whilst keep them updated independently (I think that many features/fixes can be ported from one version to the other with little to no effort).

### CODE REVIEW

**Comment by eluchsinger** [comment]
@Yuvaleros can you look into this? Actually, @panz3r  is bringing a lot of movement into this library and it could use a bit of love.

**Comment by panz3r** [comment]
Hi @Yuvaleros ,

Thanks for inviting me as a Collaborator to this project, I'll try my best to keep this project as updated as possibile.

I recently merged my previous PR #119 , bumped the version number and made a tag (`v.2.5.0`) that can be released, that would be the latest version to support older `react` version (less than `16.8`).

I'll also merge this PR soon and then proceed to rebase all my other PRs.

**Comment by Yuvaleros** [comment]
Hi @panz3r ,

Thanks for all the help and effort, I really appreciate it!

I published a version today to NPM - 2.5.0, with various merged PR's. Is it possible to change the tag to 2.6.0 and I'll release another one?

**Comment by panz3r** [comment]
Hi @Yuvaleros ,

> I published a version today to NPM - 2.5.0, with various merged PR's. Is it possible to change the tag to 2.6.0 and I'll release another one?
Of course, actually I just created the `v2.x` branch to keep working on the backward-compatible version (the one based on `react-dropzone@9.0`) and bumped the version to `2.5.1` (just a patch is enough for that)

`master` branch already contains the code based on `react-dropzone@10.x` which is no longer compatible with react versions lower than `16.8` (which I marked as `v3.0.0` 😬 ).

**Comment by panz3r** [comment]
@Yuvaleros ,

You can publish version `2.5.1` by checking out that branch.

I'd wait to release version `3.0.0` after merging PR #121 and maybe others as well.

**Comment by Yuvaleros** [comment]
@panz3r ,

Reviewed and merged the relevant PR. Great stuff!

Maybe we should add a few lines to the README warning that react versions lower than 16.8 are no longer supported and that version 2.x.x should be used, WDYT?

**Comment by panz3r** [comment]
@Yuvaleros 

> Maybe we should add a few lines to the README warning that react versions lower than 16.8 are no longer supported and that version 2.x.x should be used, WDYT?

Yeah, I think it's a great idea, I'd add a support table like this

| version | react         | material-UI  |
| ------- | ------------- | ------------ |
| `3.x`   | `16.8+`       | `4.x`        |
| `2.x`   | `15.x` or `16.x` | `3.x` or `4.x` |

**Comment by panz3r** [comment]
@Yuvaleros ,

As suggested I added the above `support` table to both the `README` and the generated docsite.

**Pull request merged**
