### PR TITLE
Extracted the PreviewImage into its own component and provided a vari…

### PR DESCRIPTION
**Pull request by max-carroll**
## Description
Extracted the PreviewImage into its own component and provided a variant for document types

## Type of change

- New feature (non-breaking change which adds functionality)

Different icons for different types of files

### CODE REVIEW

**Comment by panz3r** [comment]
Hi @max-carroll ,

Thanks for your feedback (issue #149) and contribution.

A little suggestion I'd make related to this would be to allow the customization of the PreviewImage from outside the component itself (as you suggested in the above issue) to avoid hardcoding types inside the module (which makes it not as flexible as it should be).

I'd add a prop named `getPreviewIcon` (much like the already available `get...Message` ones) which should receive the whole `fileObject` and `props` to add and return the custom icon, the default implementation for this prop would be the current one (so always return the `AttachFile` icon).

I think that this change is required to avoid binding this feature to a specific use-case and make it more flexible.

Thanks again and sorry for the delayed answer.

**Comment by max-carroll** [comment]
Thanks for the feedback @panz3r  I will have a look at this, I am working off of the master branch, is this correct? or should I work from v2.x?

**Comment by panz3r** [comment]
Hi @max-carroll ,

You can work off of `master` and then once ready backport it to `v2.x` (if that is feasible).

**Comment by max-carroll** [comment]
I am going to start a new pull request for this as to start from scratch

**Comment by panz3r** [comment]
Hi @max-carroll ,

> I am going to start a new pull request for this as to start from scratch

Thanks, I would have requested a simple rebase but if you prefer to open a new PR it's also good.
Please remember to follow the [CONTRIBUTING](https://github.com/Yuvaleros/material-ui-dropzone/blob/master/CONTRIBUTING.md) guide.

Thanks again for your support and I'm looking forward to your new PR.

**Pull request closed without merging**
