### PR TITLE
set dialog width via props

### PR DESCRIPTION
**Pull request by aflatoonSingh**
* This is add functionality for user to set any desired dialog `width` they could like to set.

### CODE REVIEW

**Comment by aflatoonSingh** [comment]
Issue number related to PR [#72 ](https://github.com/Yuvaleros/material-ui-dropzone/issues/72)

**Comment by Yuvaleros** [comment]
@aflatoonSingh Could you please add this to the documentation as well?

**Comment by aflatoonSingh** [comment]
@Yuvaleros , made updates to ` README.md`. Thank you.

**Comment by Yuvaleros** [comment]
Merging. Thanks @aflatoonSingh !

**Pull request merged**
